// 第 4 輪補充核數：對稱（內插）、射程、兩球同高（含線性阻力）、質量無關、vx 指數衰減、最高點讀數、負角 H、邊界首幀、done、頻閃間距、時間窗
import { readFileSync } from "node:fs";
const DEG = Math.PI / 180, K = 0.3;
const load = (dir, n) => JSON.parse(readFileSync(dir + "/" + n + ".json", "utf8"));
const interp = (fr, t, key) => { const i = Math.floor(t / 0.001); if (i + 1 >= fr.length) return fr[fr.length - 1].obs[key]; const a = fr[i].obs, b = fr[i + 1].obs; if (b.t === a.t) return a[key]; const s = (t - a.t) / (b.t - a.t); return a[key] + s * (b[key] - a[key]); };
const ex = (x) => x.toExponential(2);
console.log("== cond1: symmetry (h=0, no air) ==");
for (const n of ["default", "scenario-top-not-zero", "scenario-no-forward-force", "scenario-a-at-top", "scenario-range-45"]) {
  const d = load("../data", n), fr = d.frames, p = d.params; const uy = p.u * Math.sin(p.theta * DEG), tUp = uy / p.g;
  let m = 0, mv = 0; for (let tau = 0; tau <= tUp; tau += 0.001) { m = Math.max(m, Math.abs(interp(fr, tUp - tau, "y") - interp(fr, tUp + tau, "y"))); mv = Math.max(mv, Math.abs(interp(fr, tUp - tau, "vy") + interp(fr, tUp + tau, "vy"))); }
  const iz = fr.findIndex((f, i) => i > 0 && fr[i - 1].obs.vy > 0 && f.obs.vy <= 0); const a = fr[iz - 1].obs, b = fr[iz].obs; const tUpData = a.t + (b.t - a.t) * a.vy / (a.vy - b.vy); const last = fr[fr.length - 1].obs;
  console.log(n + ": tUp(data)=" + tUpData.toFixed(12) + " tUp(an)=" + tUp.toFixed(12) + " tDown=" + (last.tf - tUpData).toFixed(12) + " |tUp-tDown|=" + ex(Math.abs(last.tf - 2 * tUpData)) + " max|y(tUp-tau)-y(tUp+tau)|=" + ex(m) + " max|vy+vy'|=" + ex(mv) + " vLand=" + last.v + " u=" + p.u + " |v-u|=" + ex(Math.abs(last.v - p.u)) + " vyLand=" + last.vy + " -u sin=" + (-uy));
}
console.log("\n== cond2: range (u=15, h=0) ==");
const R = {}; for (const th of [15, 30, 45, 60, 75]) { const d = load("extra-data-r4", "angle-" + th); const last = d.frames[d.frames.length - 1].obs; R[th] = last.x; const Rs = 225 * Math.sin(2 * th * DEG) / 9.81; console.log("th=" + th + ": x=" + last.x + " R=" + Rs + " diff=" + ex(Math.abs(last.x - Rs)) + " tf=" + last.tf + " 2u sin/g=" + 2 * 15 * Math.sin(th * DEG) / 9.81); }
{ const d = load("../data", "scenario-range-45"); R[70] = d.frames[3999].obs.x; } { const d = load("../data", "default"); R[40] = d.frames[3999].obs.x; }
console.log("R40=" + R[40] + " R70=" + R[70] + " | R45 max? " + Object.entries(R).every(([k, v]) => +k === 45 || v < R[45]) + " | |R15-R75|=" + ex(Math.abs(R[15] - R[75])) + " |R30-R60|=" + ex(Math.abs(R[30] - R[60])));
{ const d = load("extra-data-r4", "official-scenario-range-45"); const f = d.frames[0]; const k = f.meta.k; for (const th of [15, 30, 45, 60, 75]) { const g = f.trails.find((q) => q.key === "ghost-" + th); console.log("ghost-" + th + ": last x/k=" + g.last[0] / k + " R=" + 225 * Math.sin(2 * th * DEG) / 9.81 + " y=" + g.last[1] + " first=" + JSON.stringify(g.first) + " n=" + g.n); } }
console.log("\n== cond3: vx spread (no air) ==");
for (const [dir, n] of [["../data", "default"], ["../data", "scenario-same-landing"], ["../data", "random-4"], ["extra-data-r4", "mass-0.1-noair"], ["extra-data-r4", "mass-5-noair"], ["extra-data-r4", "edge-u50-theta45-h50-g1.6"]]) { const d = load(dir, n); let mn = Infinity, mx = -Infinity, n0 = 0; for (const f of d.frames) { if (f.meta.landedA) break; mn = Math.min(mn, f.obs.vx); mx = Math.max(mx, f.obs.vx); n0++; } console.log(n + ": frames " + n0 + " vx " + mn + ".." + mx + " spread " + ex(mx - mn) + " u cos=" + d.params.u * Math.cos(d.params.theta * DEG)); }
console.log("\n== phenomenon 1: same height / same landing (linear drag decouples y from vx, so yB = y even with air) ==");
for (const [dir, n] of [["../data", "scenario-same-landing"], ["../data", "random-0"], ["../data", "random-4"], ["extra-data-r4", "drop-default"], ["extra-data-r4", "fast-default"], ["extra-data-r4", "air-default-m1-fast"], ["extra-data-r4", "air-u50-theta45-h50-m0.1"], ["extra-data-r4", "air-u50-theta45-h50-m5-g10"]]) {
  const d = load(dir, n), fr = d.frames; let m = 0, mx = 0; for (const f of fr) { m = Math.max(m, Math.abs(f.obs.y - f.obs.yB)); if (d.params.companion === "fast") mx = Math.max(mx, Math.abs(f.obs.xB - 2 * f.obs.x)); }
  const iA = fr.findIndex((f) => f.meta.landedA), iB = fr.findIndex((f) => f.meta.landedB); const L = fr[fr.length - 1].obs;
  console.log(n + " (comp=" + d.params.companion + ", th=" + d.params.theta.toFixed(2) + ", h=" + d.params.h.toFixed(2) + ", air=" + d.params.air + ", m=" + (+d.params.m).toFixed(3) + "): max|y-yB|=" + ex(m) + (d.params.companion === "fast" ? " max|xB-2x|=" + ex(mx) : "") + " landFrame A=" + iA + " B=" + iB + " xA=" + L.x.toFixed(4) + " xB=" + L.xB.toFixed(4) + " tf=" + L.tf.toFixed(6) + (!d.params.air ? " sqrt(2h/g)=" + Math.sqrt(2 * d.params.h / d.params.g).toFixed(6) : ""));
}
console.log("\n== mass independence (no air): mass-0.1 / mass-5 vs default ==");
{ const a = load("../data", "default"), b = load("extra-data-r4", "mass-0.1-noair"), c = load("extra-data-r4", "mass-5-noair"); let dx = 0, dE1 = 0, dE5 = 0, dW = 0; for (let i = 0; i < 4000; i++) { const o = a.frames[i].obs, p = b.frames[i].obs, q = c.frames[i].obs; dx = Math.max(dx, Math.abs(o.x - p.x), Math.abs(o.y - p.y), Math.abs(o.vx - p.vx), Math.abs(o.vy - p.vy), Math.abs(o.x - q.x), Math.abs(o.y - q.y), Math.abs(o.vx - q.vx), Math.abs(o.vy - q.vy)); dE1 = Math.max(dE1, Math.abs(p.Ek - 0.1 * o.Ek)); dE5 = Math.max(dE5, Math.abs(q.Ek - 5 * o.Ek)); const w1 = b.frames[i].arrows.find((x) => x.kind === "weight"), w5 = c.frames[i].arrows.find((x) => x.kind === "weight"); if (w1) dW = Math.max(dW, Math.abs(w1.vector[1] + 0.1 * 9.81)); if (w5) dW = Math.max(dW, Math.abs(w5.vector[1] + 5 * 9.81)); }
  console.log("x,y,vx,vy max diff=" + ex(dx) + " | Ek(0.1)-0.1*Ek(1) max=" + ex(dE1) + " | Ek(5)-5*Ek(1)=" + ex(dE5) + " | W arrow vs -mg max diff=" + ex(dW) + " | land frames " + b.frames.findIndex((f) => f.meta.landedA) + " / " + c.frames.findIndex((f) => f.meta.landedA) + " / " + a.frames.findIndex((f) => f.meta.landedA));
  console.log("scales m=0.1: " + JSON.stringify(b.frames[0].scales) + " m=5: " + JSON.stringify(c.frames[0].scales) + " (W drawn = mg*scale = " + (0.1 * 9.81 * b.frames[0].scales.weight).toFixed(6) + " / " + (5 * 9.81 * c.frames[0].scales.weight).toFixed(6) + ")"); }
console.log("\n== air: vx = ux exp(-kt/m), xInf = m ux/k, vT = mg/k ==");
for (const [dir, n] of [["extra-data-r4", "air-default-m1"], ["extra-data-r4", "air-default-m0.1"], ["extra-data-r4", "air-default-m5"], ["../data", "random-0"], ["extra-data-r4", "air-u50-theta90-h0-m0.1"], ["extra-data-r4", "air-u1-theta0-h50-m0.1"]]) {
  const d = load(dir, n), p = d.params, fr = d.frames; const ux = p.u * Math.cos(p.theta * DEG); let mx = 0, at = 0; for (const f of fr) { if (f.meta.landedA) break; const e = Math.abs(f.obs.vx - ux * Math.exp(-K * f.obs.t / p.m)); if (e > mx) { mx = e; at = f.obs.t; } }
  const iL = fr.findIndex((f) => f.meta.landedA); const L = fr[iL >= 0 ? iL : fr.length - 1].obs; const vT = p.m * p.g / K; const i2 = Math.min(fr.length - 1, 2000); const f2 = fr[i2].obs;
  console.log(n + " (m=" + (+p.m).toFixed(3) + ", g=" + p.g + "): max|vx - ux e^(-kt/m)|=" + ex(mx) + " @t=" + at.toFixed(3) + " | land t=" + L.t.toFixed(4) + " vx=" + L.vx.toFixed(5) + " (an " + (ux * Math.exp(-K * L.t / p.m)).toFixed(5) + ", " + (ux ? (L.vx / ux * 100).toFixed(1) : "-") + "% of ux) vy=" + L.vy.toFixed(4) + " vT=" + vT.toFixed(4) + " x=" + L.x.toFixed(4) + " xInf=" + (p.m * ux / K).toFixed(4) + " | t=" + f2.t.toFixed(3) + " vx/ux=" + (ux ? (f2.vx / ux).toFixed(4) : "-") + " (e^(-0.6/m)=" + Math.exp(-0.6 / p.m).toFixed(4) + ") | frame0 a=(" + fr[0].obs.ax.toFixed(4) + ", " + fr[0].obs.ay.toFixed(4) + ") exp (" + (-K / p.m * ux).toFixed(4) + ", " + (-p.g - K / p.m * p.u * Math.sin(p.theta * DEG)).toFixed(4) + ")");
}
console.log("\n== time window meta.tf vs actual landing (air: meta.tf = 1.5 x no-air tf + 0.3) ==");
for (const [dir, n] of [["../data", "random-0"], ["../data", "random-1"], ["../data", "random-2"], ["../data", "random-3"], ["extra-data-r4", "air-default-m1"], ["extra-data-r4", "air-default-m0.1"], ["extra-data-r4", "air-u50-theta45-h50-m0.1"], ["extra-data-r4", "air-u50-theta-30-h50-m0.1"], ["extra-data-r4", "air-u1-theta0-h50-m0.1"], ["extra-data-r4", "air-u50-theta90-h50-m0.1-g1.6"], ["extra-data-r4", "air-u50-theta40-h0-m1-drop"], ["extra-data-r4", "air-u50-theta45-h50-m5-g10"]]) {
  const d = load(dir, n), p = d.params, fr = d.frames; const uy = p.u * Math.sin(p.theta * DEG); const tfNo = Math.max((uy + Math.sqrt(uy * uy + 2 * p.g * p.h)) / p.g, p.companion === "none" ? 0 : Math.sqrt(2 * p.h / p.g)); const iA = fr.findIndex((f) => f.meta.landedA);
  const b = K / p.m, vT = p.g / b; const yAt = (t) => p.h + (uy + vT) / b * (1 - Math.exp(-b * t)) - vT * t; let T = 1; while (yAt(T) > 0 && T < 1e6) T *= 2; let lo = 0, hi = T; for (let i = 0; i < 200; i++) { const mid = (lo + hi) / 2; if (yAt(mid) <= 0) hi = mid; else lo = mid; } const tfAir = (p.h <= 0 && uy <= 0) ? 0 : hi;
  console.log(n + " (m=" + (+p.m).toFixed(3) + ", u=" + p.u.toFixed(1) + ", th=" + p.theta.toFixed(1) + ", h=" + p.h.toFixed(1) + ", g=" + p.g + "): meta.tf=" + fr[0].meta.tf.toFixed(3) + " 1.5*tfNo+0.3=" + (1.5 * tfNo + 0.3).toFixed(3) + " | main ball analytic landing=" + tfAir.toFixed(3) + " data landing frame=" + iA + " | covered? " + (tfAir <= fr[0].meta.tf) + " | y at meta.tf=" + yAt(Math.min(fr[0].meta.tf, tfAir)).toFixed(3) + " m");
}
console.log("\n== top readouts ==");
for (const n of ["scenario-top-not-zero", "scenario-a-at-top"]) { const d = load("../data", n), fr = d.frames; let best = fr[0]; for (const f of fr) if (Math.abs(f.obs.vy) < Math.abs(best.obs.vy)) best = f; const acc = best.arrows.find((a) => a.layer === "acceleration"), w = best.arrows.find((a) => a.layer === "weight"), vel = best.arrows.find((a) => a.layer === "velocity"); console.log(n + ": t=" + best.obs.t.toFixed(3) + " vy=" + ex(best.obs.vy) + " vx=" + best.obs.vx + " v=" + best.obs.v + " Ek=" + best.obs.Ek + " half m vx^2=" + 0.5 * d.params.m * best.obs.vx ** 2 + " y=" + best.obs.y + " H=" + best.obs.H + " a=(" + best.obs.ax + "," + best.obs.ay + ") aArrow=" + JSON.stringify(acc.vector) + " drawn=" + Math.hypot(...acc.vector) * best.scales.acceleration + " W=" + JSON.stringify(w.vector) + " drawn=" + Math.hypot(...w.vector) * best.scales.weight + " vArrow=" + JSON.stringify(vel.vector) + " meta.EkMin=" + best.meta.EkMin); }
console.log("\n== negative angle H; theta<=0 & h=0 first frame ==");
for (const [dir, n] of [["../data", "random-2"], ["../data", "random-4"], ["extra-data-r4", "edge-u50-theta-30-h50-m5"], ["extra-data-r4", "air-u50-theta-30-h50-m0.1"]]) { const d = load(dir, n), p = d.params, o = d.frames[0].obs; let ymax = -Infinity; for (const f of d.frames) ymax = Math.max(ymax, f.obs.y); console.log(n + ": th=" + p.theta.toFixed(2) + " h=" + p.h.toFixed(3) + " obs.H=" + o.H + " spec literal=" + (p.h + p.u ** 2 * Math.sin(p.theta * DEG) ** 2 / (2 * p.g)) + " actual max y=" + ymax); }
for (const n of ["edge-theta-30-h0", "edge-theta-30-h0-fast", "edge-u1-theta0-h0"]) { const d = load("extra-data-r4", n); const f = d.frames[0]; console.log(n + ": obs=" + JSON.stringify(f.obs) + " landedA=" + f.meta.landedA + " landedB=" + f.meta.landedB + " arrows=" + f.arrows.length + " bodies=" + f.bodies.map((b) => b.key).join(",") + " meta.tf=" + f.meta.tf + " done=" + f.done + " doneAt=" + d.doneAt); }
console.log("\n== air: obs.H (spec formula) vs actual max y ==");
for (const [dir, n] of [["../data", "random-0"], ["../data", "random-1"], ["extra-data-r4", "air-default-m1"], ["extra-data-r4", "air-default-m0.1"]]) { const d = load(dir, n), p = d.params; let ymax = -Infinity; for (const f of d.frames) ymax = Math.max(ymax, f.obs.y); const uy = p.u * Math.sin(p.theta * DEG); const b = K / p.m, vT = p.g / b; const tTop = Math.log(1 + uy / vT) / b; const yTop = p.h + (uy + vT) / b * (1 - Math.exp(-b * tTop)) - vT * tTop; console.log(n + ": obs.H=" + d.frames[0].obs.H.toFixed(4) + " no-air formula=" + (p.h + uy * uy / (2 * p.g)).toFixed(4) + " drag analytic max=" + yTop.toFixed(4) + " data max y=" + ymax.toFixed(4)); }
console.log("\n== done flag / clock ==");
for (const n of ["official-default", "official-scenario-same-landing", "official-random-1-long", "official-random-3-long", "air-u50-theta45-h50-m0.1", "air-u50-theta-30-h50-m0.1", "air-u50-theta40-h0-m1-drop", "edge-u50-theta-30-h50-m5", "edge-theta-30-h0"]) { const d = load("extra-data-r4", n), fr = d.frames; const i = d.doneAt; const f = i !== null ? fr[i] : null; const prev = i ? fr[i - 1] : null; console.log(n + ": doneAt=" + i + " " + (f ? "t(done)=" + f.obs.t.toFixed(6) + " landedA=" + f.meta.landedA + " landedB=" + f.meta.landedB + " prev landedA=" + prev?.meta.landedA + " landedB=" + prev?.meta.landedB + " done=" + prev?.done : "not done") + " last t=" + fr[fr.length - 1].obs.t.toFixed(6) + " tf=" + fr[fr.length - 1].obs.tf.toFixed(6) + " meta.tf=" + fr[0].meta.tf.toFixed(4) + " done=" + fr[fr.length - 1].done); }
console.log("\n== readouts after landing ==");
for (const [dir, n] of [["../data", "default"], ["../data", "random-2"], ["extra-data-r4", "air-default-m0.1"], ["extra-data-r4", "air-u50-theta45-h50-m0.1"]]) { const d = load(dir, n); const o = d.frames[d.frames.length - 1].obs; console.log(n + " last: " + JSON.stringify(o)); }
console.log("\n== strobe spacing (default, strobe-a bodies / k) ==");
{ const d = load("extra-data-r4", "official-default"); const f = d.frames[3999]; const k = f.meta.k; const pts = f.bodies.filter((b) => b.key.startsWith("strobe-a-")).sort((a, b) => +a.key.split("-")[2] - +b.key.split("-")[2]).map((b) => [b.position[0] / k, (b.position[1] - f.meta.r) / k]); const dx = pts.slice(1).map((p, i) => p[0] - pts[i][0]), dy = pts.slice(1).map((p, i) => p[1] - pts[i][1]); console.log("n=" + pts.length, "dx:", dx.map((v) => v.toFixed(6)).join(" ")); console.log("dy:", dy.map((v) => v.toFixed(4)).join(" ")); console.log("dy diff (should be -g*0.01=-0.0981):", dy.slice(1).map((v, i) => (v - dy[i]).toFixed(5)).join(" ")); }
{ const d = load("extra-data-r4", "official-scenario-same-landing"); const f = d.frames[3999]; const pa = f.bodies.filter((b) => b.key.startsWith("strobe-a-")).sort((a, b) => +a.key.split("-")[2] - +b.key.split("-")[2]), pb = f.bodies.filter((b) => b.key.startsWith("strobe-b-")).sort((a, b) => +a.key.split("-")[2] - +b.key.split("-")[2]); let m = 0; for (let i = 0; i < Math.min(pa.length, pb.length); i++) m = Math.max(m, Math.abs(pa[i].position[1] - pb[i].position[1])); console.log("same-landing strobe a/b per-image height diff max =", m, " a n=", pa.length, " b n=", pb.length); }
{ const d = load("extra-data-r4", "air-default-m1"); const f = d.frames[3999]; const k = f.meta.k; const pts = f.bodies.filter((b) => b.key.startsWith("strobe-a-")).sort((a, b) => +a.key.split("-")[2] - +b.key.split("-")[2]).map((b) => [b.position[0] / k, (b.position[1] - f.meta.r) / k]); const dx = pts.slice(1).map((p, i) => p[0] - pts[i][0]); console.log("air-default-m1 strobe dx (should decrease, ratio e^(-0.03)=0.9704):", dx.map((v) => v.toFixed(4)).join(" "), "| ratios:", dx.slice(1).map((v, i) => (v / dx[i]).toFixed(4)).join(" ")); }
console.log("\n== scale rule ==");
for (const [dir, n] of [["../data", "default"], ["../data", "random-0"], ["../data", "random-4"], ["extra-data-r4", "air-default-m0.1"], ["extra-data-r4", "air-default-m5"]]) { const d = load(dir, n); const s = d.frames[0].scales, p = d.params; const vRef = Math.sqrt(p.u ** 2 + 2 * p.g * p.h); const aMax = p.g + (p.air ? K / p.m * vRef : 0); console.log(n + ": v*vRef=" + (s.velocity * vRef).toFixed(6) + " a*aMax=" + (s.acceleration * aMax).toFixed(6) + " W*m*aMax=" + (s.weight * p.m * aMax).toFixed(6) + " fric=W " + (s.friction === s.weight) + " | aMax=" + aMax.toFixed(3) + " (g=" + p.g + ", k/m*vRef=" + (K / p.m * vRef).toFixed(3) + ")"); }
